<?php

$patina_descriptions = [
    createPattern => [
        border => "The value of each pixel is determined by the distance to the edge of the image. The closer one or more edges are, the darker the pixel will be. This pattern is not random, the same parameters create the exact same image.",
        noise_plasma => "Plasma noise is a tilable, cloudy and random pattern generated by the                 <a href='https://sdm.scad.edu/faculty/mkesson/vsfx419/wip/best/winter12/jonathan_mann/noise.html'>Diamond-Square Algorithm</a>.",
        noise_1D =>	"One dimensional noise assigns a random value to each pixel of one side of the image. Then this side gets copied all over the whole image.",
        flat => "This 'Pattern' assigns the same value to all the pixels in this color channel. So we can also generate monochrome background images with no patterns. This pattern is not random, the same parameters create the exact same image.",
        wave => "The wave patterns are calculated using the sine function. That gives us smooth lines in different directions. This pattern is not random, the same parameters create the exact same image.",
        noise_white => "With white noise every pixel gets a random value with no respect to the neighbouring pixels.",
        slope => "ToDo: changing directions has to be possible. For now, the slope pattern has no options and creates the same thing everytime. I will expand this when i need another slope. This pattern is not random, the same parameters create the exact same image."
    ],
    filter => [
        blur => "The blur filter is not yet suitable for tilable patterns because it does not wrap around the edges. Copied from <a href='http://blog.ivank.net/fastest-gaussian-blur.html'>http://blog.ivank.net/fastest-gaussian-blur.html</a>.",
        brightness => "The brightness filter can be positive to brighten the color channel or negative to darken it. The filter keeps black and white and manipulates the color-curve between them.",
        contrast => "The contrast filter uses a linear function to calculate the result. You can specify two parameters: the slope m and an x-coordinate that dictates where the center of the line should be moved.",
        invert => "The invert filter takes no arguments and just inverts the image.",
        threshold => "This filter is like contrast to the max. Everything about a given treshold gets white or 100% brightness and everything below it gets black or zero."
    ]
];

$patina_contentStaticSite = [
    blur => <<<EOT
            <h2>Options / Parameters</h2>
            <p class="copy">The blur filter takes only one parameter:</p>
            <dl class="copy parameters">
                <dt>radius</dt>
                <dd>
                    possible values are positive numbers:
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "blur", "radius": 5 }]
                            }
                        }'
                    ></div> 3 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "blur", "radius": 1 }]
                            }
                        }'
                    ></div> 1
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "blur", "radius": 10 }]
                            }
                        }'
                    ></div> 10
                </dd>
            </dl>
    EOT,

    brightness => <<<EOT
            <h2>Options / Parameters</h2>
            <p class="copy">The brightness filter takes only one parameter:</p>
            <dl class="copy parameters">
                <dt>brightness</dt>
                <dd>
                    possible values are positive numbers:
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "brightness", "brightness": -4 }]
                            }
                        }'
                    ></div> -4
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "brightness" }]
                            }
                        }'
                    ></div> 0 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "brightness", "brightness": 2 }]
                            }
                        }'
                    ></div> 2
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "brightness", "brightness": 8 }]
                            }
                        }'
                    ></div> 8
                </dd>
            </dl>
    EOT,

    noise_1D => <<<EOT
            <h2>Options / Parameters</h2>
                
            <dl class="copy parameters">
                <dt>direction</dt>
                <dd>
                    possible values are these strings:
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_1D",
                                    "direction"     : "horizontal"
                                }
                            }
                        }'
                    ></div> horizontal (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_1D",
                                    "direction"     : "vertical"
                                }
                            }
                        }'
                    ></div> vertical
                </dd>
            </dl>`
    EOT,

    threshold => <<<EOT
            <h2>Options / Parameters</h2>
            <p class="copy">The threshold filter takes one parameter:</p>
            <dl class="copy parameters">
                <dt>threshold</dt>
                <dd>
                    possible values are numbers numbers between 0 and 1 (ToDo: use everywhere the same range. 0-255, 0-1, or 0-99/100):
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "threshold" }]
                            }
                        }'
                    ></div> 0.5 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "threshold", "threshold": 0.1 }]
                            }
                        }'
                    ></div> 0.1
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "patternName"   : "noise_plasma",
                                "filter"        : [{ "name": "threshold", "threshold": 0.85 }]
                            }
                        }'
                    ></div> 0.85
                </dd>
            </dl>`,
    EOT,

    wave => <<<EOT
            <h2>Options / Parameters</h2>
            <dl class="copy parameters">
                <dt>direction</dt>
                <dd>
                    possible values are these strings:
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "vertical"
                                }
                            }
                        }'
                    ></div> vertical (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "horizontal",
                                    "frequency"     : 20
                                }
                            }
                        }'
                    ></div> horizontal
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "diagonalUp"
                                }
                            }
                        }'
                    ></div> diagonalUp
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "diagonalDown"
                                }
                            }
                        }'
                    ></div> diagonalDown
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "concentric",
                                    "frequency"     : 20
                                }
                            }
                        }'
                    ></div> concentric
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "rectangles"
                                }
                            }
                        }'
                    ></div> rectangles
                </dd>

                <dt>frequency</dt>
                <dd>
                    defines how many 'waves' per width you get. Possible values are numbers. Negative numbers invert the pattern.
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave"
                                }
                            }
                        }'
                    ></div> 5 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "frequency"     : 2
                                }
                            }
                        }'
                    ></div> 2
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "frequency"     : -2
                                }
                            }
                        }'
                    ></div> -2
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "frequency"     : 20
                                }
                            }
                        }'
                    ></div> 20
                </dd>

                <dt>offsetX | offsetY</dt>
                <dd>
                    you can slide the pattern up, down, left and right. Possible values are numbers.
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "concentric"
                                }
                            }
                        }'
                    ></div> 0 | 0 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "concentric",
                                    "offsetY"       : 15
                                }
                            }
                        }'
                    ></div> 0 | 15

                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "wave",
                                    "direction"     : "concentric",
                                    "offsetX"       : 100,
                                    "offsetY"       : 5
                                }
                            }
                        }'
                    ></div> 100 | 5
                </dd>
            </dl>

            <h2>Playground</h2>

            <p class="copy">Here you can test this pattern. Change the values inside the textarea or rewrite it completely, then hit "apply".</p>

            <div class="pattern">

                <div id="js_patina_fromTextarea" 
                    class="pattern__thumbnails pattern__thumbnails--256"
                ></div
                ><button id="js_patina_CallToAction" class="button button__applyPatinaTextarea">&UpperLeftArrow;<br>apply</button>

                <textarea id="js_patina_textarea" rows="13" class="code" style="margin-top: 0;">
            {
                "patina"    : {
                    "type"      : "createPattern",
                    "pattern"   : {
                        "name"      : "wave",
                        "direction" : "rectangles",
                        "frequency" : 2,
                        "offsetX"   : 64,
                        "offsetY"   : 0
                    }
                }
            }
                </textarea>
            
                <script type="module" src="scripts/main.js"></script>
                <script>
                    const trigger  = document.getElementById('js_patina_CallToAction');
                    const textarea = document.getElementById('js_patina_textarea');
                    const target   = document.getElementById('js_patina_fromTextarea');

                    // ich importiere von /patina... weil die dynamische und die statische Version 
                    // der seite unterschiedliche base href haben und der relative Pfad nicht funktioniert hat
                    const calculatePatinaFromTextarea = function () {
                        import('/patina/scripts/modules/mel_patina.js')
                            .then((patina) => {
                                new patina.default(target, textarea.value);
                            });
                    };

                    trigger.addEventListener('click', calculatePatinaFromTextarea);
                    calculatePatinaFromTextarea();
                </script>   
            </div><!-- .pattern -->
    EOT,

    noise_plasma => <<<EOT
            <h2>Options / Parameters</h2>
            <dl class="copy parameters">

                <dt>frequency</dt>
                <dd>
                    defines how many 'waves' per width you get. Possible values are positive numbers up to ½ of the image width. Everything above that will give you a flat image.
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_plasma"
                                }
                            }
                        }'
                    ></div> 1 (default)
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_plasma",
                                    "frequency"     : 2
                                }
                            }
                        }'
                    ></div> 2
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_plasma",
                                    "frequency"     : 10
                                }
                            }
                        }'
                    ></div> 10
                    <br />
                    <div class="js-module pattern__thumbnails pattern__thumbnails--lineHeight" 
                        data-module-name="patina" 
                        data-module-data='{
                            "patina": {
                                "type"          : "createPattern",
                                "pattern"       : {
                                    "name"          : "noise_plasma",
                                    "frequency"     : 20
                                }
                            }
                        }'
                    ></div> 20
                </dd>

            </dl>


            <h2>Playground</h2>

            <p class="copy">Here you can test this pattern. Change the values inside the textarea or rewrite it completely, then hit "apply".</p>

            <div class="pattern">
                <div id="js_patina_fromTextarea" 
                    class="pattern__thumbnails pattern__thumbnails--256"
                    style=width:200px
                ></div
                ><button id="js_patina_CallToAction" class="button button__applyPatinaTextarea">&UpperLeftArrow;<br>apply</button>

                <textarea id="js_patina_textarea" rows="13" class="code" style="margin-top: 0;">
            {
                "patina"    : {
                    "type"      : "createPattern",
                    "pattern"   : {
                        "name"      : "noise_plasma",
                        "frequency" : 3
                    }
                }
            }
                </textarea>

                <script type="module" src="scripts/main.js"></script>
                <script>
                    const trigger  = document.getElementById('js_patina_CallToAction');
                    const textarea = document.getElementById('js_patina_textarea');
                    const target   = document.getElementById('js_patina_fromTextarea');

                    // ich importiere von /patina... weil die dynamische und die statische Version 
                    // der seite unterschiedliche base href haben und der relative Pfad nicht funktioniert hat
                    const calculatePatinaFromTextarea = function () {
                        import('/patina/scripts/modules/mel_patina.js')
                            .then((patina) => {
                                new patina.default(target, textarea.value);
                            });
                    };

                    trigger.addEventListener('click', calculatePatinaFromTextarea);
                    calculatePatinaFromTextarea();
                </script>
            </div><!-- .pattern -->
    EOT
]; ?>